import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Single auto-generated sidebar over content/. Each top-level dir becomes a category.
  main: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
