"""Export a compact context file for Claude to read at session start.

Writes knowledge/agent_context.md with:
  - project mission (one paragraph)
  - current taxonomy snapshot
  - node counts by type
  - latest 5 reports
  - list of active skills (skills/*/*/SKILL.md)

Run after every ingestion batch.
"""
from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

import yaml

from _paths import (
    CONTEXT_FILE,
    EDGES_FILE,
    KNOWLEDGE,
    NODES_FILE,
    REPORTS,
    REPO_ROOT,
    TAXONOMIES,
)


def load_yaml(path: Path):
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def main() -> int:
    parts: list[str] = []
    parts.append("# Pathology-Wiki — Agent Context")
    parts.append("")
    parts.append("Auto-generated by `scripts/python/export_claude_context.py`. Do not hand-edit.")
    parts.append("")

    # Mission
    parts.append("## Mission")
    parts.append(
        "Pathology-Wiki is an agent-extensible knowledge base for computational pathology. "
        "Every object produces five artifacts (YAML, graph entries, MDX, SKILL.md, site data). "
        "See CLAUDE.md §2."
    )
    parts.append("")

    # Node counts
    if NODES_FILE.exists():
        nodes = (load_yaml(NODES_FILE) or {}).get("nodes", [])
        counts = Counter(n["type"] for n in nodes)
        parts.append("## Node counts")
        for t, c in sorted(counts.items()):
            parts.append(f"- {t}: {c}")
        parts.append(f"- **total**: {len(nodes)}")
    else:
        parts.append("## Node counts")
        parts.append("- nodes.yaml not found")
    parts.append("")

    # Edge counts
    if EDGES_FILE.exists():
        edges = (load_yaml(EDGES_FILE) or {}).get("edges", [])
        ec = Counter(e["type"] for e in edges)
        parts.append("## Edge counts")
        for t, c in sorted(ec.items()):
            parts.append(f"- {t}: {c}")
        parts.append(f"- **total**: {len(edges)}")
        parts.append("")

    # Taxonomies
    if TAXONOMIES.exists():
        parts.append("## Taxonomy files")
        for p in sorted(TAXONOMIES.glob("*.yaml")):
            parts.append(f"- {p.relative_to(REPO_ROOT)}")
        parts.append("")

    # Skills
    skills_root = REPO_ROOT / "skills"
    if skills_root.exists():
        parts.append("## Active skills")
        for p in sorted(skills_root.rglob("SKILL.md")):
            parts.append(f"- {p.relative_to(REPO_ROOT)}")
        parts.append("")

    # Latest reports
    if REPORTS.exists():
        reports = sorted(REPORTS.glob("*.md"), reverse=True)[:5]
        if reports:
            parts.append("## Latest 5 reports")
            for p in reports:
                parts.append(f"- {p.relative_to(REPO_ROOT)}")
            parts.append("")

    CONTEXT_FILE.parent.mkdir(parents=True, exist_ok=True)
    CONTEXT_FILE.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {CONTEXT_FILE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
